core/apps/accounts/urls.py
from django.urls import path, include
from apps.accounts import views as views

# _______________________________________________________

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    # api-v1
    path(
        'api/v1/',
        include('apps.accounts.api.v1.urls', namespace='api-v1'),
        name='api-v1',
    ),
]

# _______________________________________________________

core/apps/blog/urls.py
from django.urls import path, include
from apps.blog import views as views

# _______________________________________________________

app_name = 'blog'

urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("post-list/", views.ArticleListView.as_view(), name='post-list'),
    path("create-post/", views.CreateArticleView.as_view(), name='create-post'),
    path("update-post/<str:slug>/", views.UpdatePostView.as_view(), name='update-post'),
    path("delete-post/<str:slug>/", views.DeletePostView.as_view(), name='delete-post'),
    path("blog/", views.BlogView.as_view(), name='posts'),
    path("blog/<str:slug>/", views.PostDetailsView.as_view(), name='post-details'),
    # api-v1
    path("blog/api/v1/", include("apps.blog.api.v1.urls"), name='api-v1'),
]

# _______________________________________________________

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# _______________________________________________________

# swagger config
# ===============
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="API Docs by Swagger",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

# _______________________________________________________

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "accounts/",
        include("apps.accounts.urls", namespace="accounts"),
        name="accounts",
    ),
    path("", include("apps.blog.urls", namespace="blog"), name="blog"),
    path("", include("apps.comments.urls", namespace="comments"), name="comments"),
    # Basic Auth for DRF
    path("api-auth/", include("rest_framework.urls")),
    # swagger
    path(
        'swagger/outout.json/',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json',
    ),
    path(
        'swagger/',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui',
    ),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# _______________________________________________________

core/templates/partials/footer.html
    <footer>
        <div class="container">
            <p>© 2025 MySite. All rights reserved.</p>
        </div>
    </footer>

core/templates/partials/header.html
    <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand fw-bold" href="{% url 'blog:index' %}">MySite</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item btn btn-success mx-1"><a class="nav-link text-white" href="{% url 'blog:post-list' %}">پست های نویسنده</a></li>                    
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a></li>
                    {% else %}
                    <li class="nav-item btn btn-light"><a class="nav-link" href="{% url 'accounts:login' %}">ورود</a></li>
                    <li class="nav-item btn btn-light"><a class="nav-link" href="{% url 'accounts:register' %}">ثبت‌نام</a></li>
                    {% endif %}
                                     
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item btn btn-warning mx-1"><a class="nav-link" href="/swagger/">API Docs</a></li>
                    <li class="nav-item btn btn-primary mx-1"><a class="nav-link text-white" href="{% url 'blog:api-v1:posts' %}">API Posts</a></li>
                </ul>
            </div>
        </div>
    </nav>

core/templates/partials/messages.html
    <script>

        document.addEventListener("DOMContentLoaded", function () {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": true,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
            
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    toastr.success("{{ message }}");
                {% elif message.tags == 'error' %}
                    toastr.error("{{ message }}");
                {% elif message.tags == 'warning' %}
                    toastr.warning("{{ message }}");
                {% elif message.tags == 'info' %}
                    toastr.info("{{ message }}");
                {% endif %}
            {% endfor %}        
            
                
        });

    </script>

core/templates/partials/scripts.html
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <!-- toastr-Alert---------------------------------->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>