core/apps/accounts/urls.py
from django.urls import path, include
from apps.accounts import views as views

# _______________________________________________________

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    # api-v1
    path(
        'api/v1/',
        include('apps.accounts.api.v1.urls', namespace='api-v1'),
        name='api-v1',
    ),
]

# _______________________________________________________

core/apps/blog/api/v1/urls.py
from django.urls import path, include
from apps.blog.api.v1 import views as views

# _______________________________________________________

app_name = 'api-v1'

urlpatterns = [
    path("posts/", views.PostListApiView.as_view(), name='posts'),
    path("posts/<str:slug>/", views.PostDetailsApiView.as_view(), name='post_details'),
]
# _______________________________________________________

core/apps/blog/urls.py
from django.urls import path, include
from apps.blog import views as views

# _______________________________________________________

app_name = 'blog'

urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("post-list/", views.ArticleListView.as_view(), name='post-list'),
    path("create-post/", views.CreateArticleView.as_view(), name='create-post'),
    path("update-post/<str:slug>/", views.UpdatePostView.as_view(), name='update-post'),
    path("delete-post/<str:slug>/", views.DeletePostView.as_view(), name='delete-post'),
    path("blog/", views.BlogView.as_view(), name='posts'),
    path("blog/<str:slug>/", views.PostDetailsView.as_view(), name='post-details'),
    # api-v1
    path("blog/api/v1/", include("apps.blog.api.v1.urls"), name='api-v1'),
]

# _______________________________________________________

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

# _______________________________________________________

# swagger config
# ===============
schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="API Docs by Swagger",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

# _______________________________________________________

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "accounts/",
        include("apps.accounts.urls", namespace="accounts"),
        name="accounts",
    ),
    path("", include("apps.blog.urls", namespace="blog"), name="blog"),
    path("", include("apps.comments.urls", namespace="comments"), name="comments"),
    # Basic Auth for DRF
    path("api-auth/", include("rest_framework.urls")),
    # swagger
    path(
        'swagger/outout.json/',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json',
    ),
    path(
        'swagger/',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui',
    ),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# _______________________________________________________

core/apps/blog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import datetime
import os
from utils import get_random_code
from django.dispatch import receiver
from django.db.models.signals import pre_delete

# _______________________________________________________


class Category(models.Model):
    category_title = models.CharField(max_length=100, verbose_name=_("عنوان دسته"))
    summary_description = models.CharField(
        max_length=200, null=True, blank=True, verbose_name=_("توضیحات")
    )
    created_date = models.DateTimeField(
        auto_now_add=True, verbose_name=_("تاریخ ایجاد")
    )
    is_active = models.BooleanField(default=True, verbose_name=_("فعال/غیرفعال"))

    def __str__(self):
        return self.category_title

    class Meta:
        verbose_name = "دسته بندی مقاله"
        verbose_name_plural = "دسته بندی مقاله ها"


# _______________________________________________________


def upload_image_article(instance, filename):
    file, exe = os.path.splitext(filename)
    file_name = f'images/blog/article/{file}{get_random_code(5)}{exe}'
    return file_name


class Article(models.Model):
    article_title = models.CharField(max_length=100, verbose_name=_("عنوان مقاله"))
    article_text = models.TextField(null=True, blank=True, verbose_name=_("متن مقاله"))
    is_active = models.BooleanField(default=True, verbose_name=_("فعال/غیرفعال"))
    created_date = models.DateTimeField(
        auto_now_add=True, verbose_name=_("تاریخ ایجاد")
    )
    updated_date = models.DateTimeField(auto_now=True, verbose_name=_("تاریخ ویرایش"))
    published_date = models.DateTimeField(
        default=datetime.now, verbose_name=_("تاریخ انتشار")
    )
    slug = models.SlugField(max_length=500, null=True, blank=True, allow_unicode=True)
    image_name = models.ImageField(
        upload_to=upload_image_article, verbose_name=_("عکس مقاله")
    )
    author = models.ForeignKey(
        "accounts.Profile",
        verbose_name=_("نویسنده"),
        on_delete=models.CASCADE,
        related_name="articles",
    )
    category = models.ForeignKey(
        Category,
        verbose_name=_("دسته بندی"),
        on_delete=models.CASCADE,
        related_name="articles",
    )

    def __str__(self):
        return self.article_title

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقاله ها"


# _______________________________________________________


@receiver(pre_delete, sender=Article)
def delete_article_images(sender, instance, **kwargs):
    """Remove image_name field before delete article object"""
    if instance.image_name and os.path.isfile(instance.image_name.path):
        os.remove(instance.image_name.path)


# _______________________________________________________

core/apps/blog/forms.py
from django import forms
from .models import Article, Category

# _______________________________________________________


class ArticleForm(forms.ModelForm):
    article_title = forms.CharField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    article_text = forms.CharField(
        max_length=1000,
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control', "rows": "5"}),
    )

    category = forms.ModelChoiceField(
        queryset=Category.objects.filter(is_active=True),
        required=True,
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    image_name = forms.ImageField(
        required=True, widget=forms.FileInput(attrs={"accept": ".jpg,.jpeg,.png,.webp"})
    )

    slug = forms.SlugField(
        allow_unicode=True,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = Article
        fields = ['article_title', 'article_text', 'image_name', 'category', 'slug']


# _______________________________________________________

core/apps/blog/api/v1/views.py
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import permissions
from rest_framework import status
from .serializers import PostSerializer
from django.shortcuts import get_object_or_404
from ...models import Article
from .permissions import IsOwnerOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter

# _______________________________________________________


class PostListApiView(generics.ListCreateAPIView):
    """
    Getting and Creating posts with api
    """

    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["category"]
    search_fields = ["article_title", "id"]
    ordering_fields = ["published_date"]

    def get_queryset(self):
        articles = Article.objects.filter(is_active=True)
        articles = self.filter_queryset(articles)
        return articles

    def get(self, request, *args, **kwargs):
        ser_data = self.get_serializer(instance=self.get_queryset(), many=True)
        return Response(data=ser_data.data, status=status.HTTP_200_OK)

    def post(self, request, *args, **kwargs):
        ser_data = self.get_serializer(data=request.data)
        ser_data.is_valid(raise_exception=True)
        ser_data.save()
        return Response(
            data={"details": "The post was successfully created."},
            status=status.HTTP_201_CREATED,
        )


# _______________________________________________________


class PostDetailsApiView(generics.RetrieveUpdateDestroyAPIView):
    """
    Getting, editing, deleting post details with api
    """

    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    lookup_field = 'slug'
    lookup_url_kwarg = 'post_details'

    def get_object(self):
        post = get_object_or_404(Article, slug=self.kwargs['slug'])
        return post

    def get(self, request, *args, **kwargs):
        ser_data = self.get_serializer(instance=self.get_object())
        return Response(data=ser_data.data, status=status.HTTP_200_OK)

    def put(self, request, *args, **kwargs):
        ser_data = self.get_serializer(instance=self.get_object(), data=request.data)
        ser_data.is_valid(raise_exception=True)
        ser_data.save()
        return Response(data=ser_data.data, status=status.HTTP_200_OK)

    def patch(self, request, *args, **kwargs):
        ser_data = self.get_serializer(
            instance=self.get_object(), data=request.data, partial=True
        )
        ser_data.is_valid(raise_exception=True)
        ser_data.save()
        return Response(data=ser_data.data, status=status.HTTP_200_OK)

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


# _______________________________________________________

core/apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Article
from apps.accounts.models import Profile
from .forms import ArticleForm
from django.urls import reverse_lazy
from django.conf import settings
from django.views import View
from apps.comments.models import BlogComment
from django.core.cache import cache
from django.dispatch import receiver
from django.db.models.signals import post_save, post_delete

# _______________________________________________________


def media_admin(request):
    """
    Function to receive media files inside templates
    """
    return {"media_url": settings.MEDIA_URL}


# _______________________________________________________


class IndexView(TemplateView):
    template_name = 'blog/index.html'


# _______________________________________________________


class ArticleListView(LoginRequiredMixin, ListView):
    """
    List of active posts by an author
    """

    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    ordering = '-published_date'

    def get_queryset(self):
        profile = get_object_or_404(Profile, user=self.request.user)
        return Article.objects.filter(is_active=True, author=profile)


# _______________________________________________________


class CreateArticleView(LoginRequiredMixin, CreateView):
    """
    Creating a post by the author logged in
    """

    template_name = 'blog/create_post.html'
    form_class = ArticleForm
    success_url = reverse_lazy('blog:post-list')
    model = Article

    def form_valid(self, form):
        profile = get_object_or_404(Profile, user=self.request.user)
        form.instance.author = profile
        form.save()
        return super().form_valid(form)


# _______________________________________________________


class UpdatePostView(LoginRequiredMixin, UpdateView):
    """
    Current post updated by logged in author
    """

    template_name = 'blog/update_post.html'
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('blog:post-list')

    def get_queryset(self):
        profile = get_object_or_404(Profile, user=self.request.user)
        return Article.objects.filter(is_active=True, author=profile)


# _______________________________________________________


class DeletePostView(LoginRequiredMixin, DeleteView):
    """
    Deleting the post by the author entered
    """

    template_name = 'blog/delete_post.html'
    model = Article
    context_object_name = 'post'
    success_url = reverse_lazy('blog:post-list')

    def get_queryset(self):
        profile = get_object_or_404(Profile, user=self.request.user)
        return Article.objects.filter(is_active=True, author=profile)


# _______________________________________________________


class PostDetailsView(DetailView):
    """
    Displaying the details of a post and registering comments for it, as well as displaying user comments
    """

    template_name = 'blog/blog_details.html'
    model = Article
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = get_object_or_404(Article, slug=self.kwargs['slug'])
        comments = BlogComment.objects.filter(is_active=True, article=article).order_by(
            "-published_date"
        )

        context["comments"] = comments
        return context


# _______________________________________________________


class BlogView(View):
    """
    View List of active articles and sort by last article
    """

    template_name = 'blog/blog_list.html'

    def get(self, request, *args, **kwargs):
        """
        Caching the article data for 10 minutes
        """
        cache_key = "articles"
        data = cache.get(cache_key)
        if not data:
            posts = Article.objects.filter(is_active=True).order_by('-published_date')
            cache.set(cache_key, posts, timeout=10 * 60)
            data = posts
        return render(request, self.template_name, {"posts": data})


# _______________________________________________________


@receiver([post_save, post_delete], sender=Article)
def clear_product_cache(sender, **kwargs):
    """
    Deleting the cache of articles when it is created or deleted
    """
    cache.delete("articles")


# _______________________________________________________

core/templates/blog/blog_details.html
{% extends 'main_template.html' %}
{% load render_partial %}

{% block title %}
جزئیات مقاله
{% endblock title %}


{% block content %}
    <div class="container py-5">
        <div class="card shadow-sm mb-5">
            <img src="{{media_url}}{{post.image_name}}" style="width:500px;height:auto;margin:0 auto;padding:10px 0"
                class="card-img-top" alt="{{post.article_title}}">
            <div class="card-body">
                <h3 class="card-title">{{post.article_title}}</h3><br>
                <p class="text-muted small">تاریخ ایجاد: <strong>{{post.published_date | date:"Y/m/d"}}</strong></p>
                <p class="text-muted small">دسته بندی : <strong>{{post.category}}</strong></p>
                <p class="card-text">{{post.article_text}}</p>
            </div>
        </div>
        
        <!-- Comment List -->
        <div class="card shadow-sm mb-4">
            <div class="card-body">
                <h4 class="mb-4">دیدگاه‌ها</h4>                
                {% if comments %}
                    {% for comment in comments %}
                        <div class="d-flex mb-4">
                            <img src="https://cdn-icons-png.flaticon.com/512/847/847969.png" alt="user" class="rounded-circle me-3 mx-3"
                                width="60" height="60">
                            <div>
                                <h6 class="mb-2 fw-bold">{{comment.fullname}}</h6>
                                <p class="mb-0">{{comment.comment_text}}</p>
                            </div>
                        </div>                    
                    {% endfor %}  
                    {% else %}
                    <h3 class="text-secondary text-center">دیدگاه برای این پست درج نشده است.</h3>                     
                {% endif %}                                                     
            </div>
        </div>
        <div class="card shadow-sm">
            <div class="card-body">
                <h4 class="mb-4">ارسال دیدگاه</h4>
                {% if user.is_authenticated %}
                    {% render_partial 'comments:blog-comment' slug=post.slug %}
                {% else %}
                    <h4 class="text-danger m-auto">برای درج نظر باید ابتدا <a class="btn btn-primary text-decoration-none" href="{% url 'accounts:login' %}">وارد</a> شوید</h4>                 
                {% endif %}  
                
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/blog/blog_list.html
{% extends 'main_template.html' %}


{% block title %}
مقالات
{% endblock title %}


{% block content %}
    <div class="container py-5">
        <h2 class="mb-4 text-center">لیست پست‌ها</h2>
        <div class="row g-4">
            
            {% for post in posts %}
                <div class="col-md-4">
                    <div class="card h-100 shadow-sm">
                        <img src="{{media_url}}{{post.image_name}}" class="card-img-top" alt="{{post.article_title}}">
                        <div class="card-body">
                            <h5 class="card-title">{{post.article_title}}</h5>
                            <p class="card-text text-muted small">تاریخ انتشار: {{post.published_date | date:"Y/m/d"}}</p>
                            <p class="card-text">دسته بندی : {{post.category}}</p>
                            <a href="{% url 'blog:post-details' post.slug %}" class="btn btn-outline-primary">جزئیات</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
                
        </div>
    </div>
{% endblock content %}

core/templates/blog/create_post.html
{% extends 'main_template.html' %}


{% block title %}
    ایجاد پست
{% endblock title %}


{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h3 class="card-title mb-4 text-center">درج پست جدید</h3>
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label class="form-label">عنوان پست</label>
                                {{form.article_title}}
                            </div>
                            <div class="mb-3">
                                <label class="form-label">توضیحات پست</label>
                                {{form.article_text}}
                            </div>
                            <div class="mb-3">
                                <label class="form-label">slug</label>
                                {{form.slug}}
                            </div>
                            <div class="mb-3">
                                <div class="form-group">
                                    <label for="id_category">دسته بندی</label>
                                    {{form.category}}
                                </div>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">آپلود تصویر</label>
                                {{form.image_name}}
                            </div>
                            <button type="submit" class="btn btn-primary w-100">ذخیره پست</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/blog/delete_post.html
{% extends 'main_template.html' %}


{% block title %}
حذف پست
{% endblock title %}


{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm border-danger">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="card-body text-center">
                            <h4 class="text-danger mb-3">آیا از حذف این پست مطمئن هستید؟</h4>
                            <p>عنوان پست: <strong>{{post.article_title}}</strong></p>
                            <div class="d-flex justify-content-center gap-3 mt-4">
                                <button type="submit" class="btn btn-danger">بله، حذف شود</button>
                                <a href="{% url 'blog:post-list' %}" class="btn btn-secondary">انصراف</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/blog/index.html
{% extends 'main_template.html' %}


{% block title %}
    صفحه اول
{% endblock title %}


{% block content %}
    <section class="hero-section">
        <div class="hero-overlay"></div>
        <div class="hero-content container">
            <h1 class="display-5 fw-bold mb-3">به وبلاگ ما خوش آمدید</h1>
            <p class="lead mb-4">مطالب جذاب و آموزشی در زمینه برنامه‌نویسی، تکنولوژی و دنیای دیجیتال</p>
        </div>
    </section>

    <div class="container py-5">
        <div class="text-center mt-1">
            <a href="{% url 'blog:posts' %}" class="btn btn-primary btn-lg">مشاهده همه پست‌ها</a>
        </div>
    </div>
{% endblock content %}

core/templates/blog/post_list.html
{% extends 'main_template.html' %}


{% block title %}
لیست پست ها
{% endblock title %}


{% block content %}
    <div class="container py-5">
        <h3 class="mb-4 text-center">پست‌های من</h3>
        <div class="table-responsive">
            <table class="table table-striped align-middle">
                <a href="{% url 'blog:create-post' %}" class="btn btn-primary btn-sm my-3">+ پست جدید</a>
                <thead>
                    <tr>
                        <th>عنوان پست</th>
                        <th>تاریخ انتشار</th>
                        <th>وضعیت</th>
                        <th>نویسنده</th>
                        <th>عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for post in posts %}
                        <tr>
                            <td>{{post.article_title}}</td>
                            <td>{{post.published_date}}</td>
                            <td>
                                
                                {% if post.is_active %}
                                    فعال
                                    {% else %}
                                    غیرفعال
                                {% endif %}
                                    
                            </td>
                            <td>
                                {{post.author}}
                            </td>
                            <td>
                                <a href="{% url 'blog:post-details' post.slug %}" class="btn btn-sm btn-info">جزئیات</a>
                                <a href="{% url 'blog:update-post' post.slug %}" class="btn btn-sm btn-success">ویرایش</a>
                                <a href="{% url 'blog:delete-post' post.slug %}" class="btn btn-sm btn-danger">حذف</a>
                            </td>
                        </tr>                        
                    {% endfor %}
                        

                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

core/templates/blog/update_post.html
{% extends 'main_template.html' %}


{% block title %}
    ویرایش پست
{% endblock title %}


{% block content %}
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h3 class="card-title mb-4 text-center">ویرایش پست</h3>
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label class="form-label">عنوان پست</label>
                                {{form.article_title}}
                            </div>
                            <div class="mb-3">
                                <label class="form-label">توضیحات پست</label>
                                {{form.article_text}}
                            </div>
                            <div class="mb-3">
                                <label class="form-label">slug</label>
                                {{form.slug}}
                            </div>
                            <div class="mb-3">
                                <div class="form-group">
                                    <label for="id_category">دسته بندی</label>
                                    {{form.category}}
                                </div>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">آپلود تصویر</label>
                                {{form.image_name}}
                            </div>
                            <button type="submit" class="btn btn-primary w-100">ویرایش پست</button>
                            <a class="btn btn-danger w-100 my-2" href="{% url 'blog:post-list' %}">بازگشت</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}